language: python
sudo: false
os:
  - linux
python:
  - '2.6'
  - '2.7'
  - '3.3'
  - '3.4'
  - '3.5'
  - '3.6'
install:
  - pip install -U pip
  - pip install -U tox-travis
  - pip install coveralls
  - pip install coverage
  - cp tests/testrail.conf ~/.testrail.conf
script: tox -v --recreate
after_success:
  - coveralls
